---
title: "Allocation Report"
author: "Matthew Kuperus Heun"
date: '`r parsedate::format_iso_8601(Sys.time())`'
output: pdf_document
knit: (function(inputFile, encoding) 
        {rmarkdown::render(inputFile, 
                           encoding = encoding,
                           output_file = paste0(substr(inputFile,1,nchar(inputFile)-4), "-", Sys.Date(),'.pdf'),
                           output_dir = paste0(PFUSetup::get_abs_paths()$reports_dest_folder, "/Allocation Reports/", Sys.Date(), sep = "")
                           ) 
        })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
library(ggplot2)
library(knitr)
library(magrittr)
library(MKHthemes)
library(parsedate)
library(rprojroot)
library(SEAPSUTWorkflow)

# Set up the root directory
root <- rprojroot::is_rstudio_project
# And the cache
cache_path <- root$find_file(".drake")
```

## Introduction

This report shows graphs of all final energy allocations to final-to-useful machines.

Note that numbers following "##" are the row number in the `AllocationGraphs` data frame.


```{r, echo = FALSE}
alloc_plots <- drake::readd(SEAPSUTWorkflow::target_names$AllocationGraphs, 
                            path = cache_path, 
                            character_only = TRUE) %>% 
  magrittr::extract2("Plots")
```


```{r, fig.width=6.5, fig.height=2.5, echo=FALSE}
alloc_plots[1:10]

```




