---
title: "Allocation Report"
author: "Matthew Kuperus Heun"
date: '`r parsedate::format_iso_8601(Sys.time())`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
library(ggplot2)
library(knitr)
library(magrittr)
library(MKHthemes)
library(parsedate)
library(rprojroot)
library(SEAPSUTWorkflow)

# Set up the root directory
root <- rprojroot::is_rstudio_project
# And the cache
cache_path <- root$find_file(".drake")
```

## Introduction

Put an introduction here.


## Residential electricity

This is a sample graph showing the world allocation of residential electricity over time.

<!-- ```{r, echo = FALSE} -->
<!-- residential_elect <- function(.df) { -->
<!--   .df %>% -->
<!--     ggplot2::ggplot(mapping = ggplot2::aes(x = .data[[IEATools::iea_cols$year]], -->
<!--                                            y = .data[[IEATools::template_cols$.values]], -->
<!--                                            fill = .data[[IEATools::template_cols$machine]])) + -->
<!--     ggplot2::geom_area() + -->

<!--     ggplot2::facet_grid(rows = ggplot2::vars(.data[[IEATools::iea_cols$country]]), -->
<!--                         cols = ggplot2::vars(.data[[IEATools::template_cols$destination]])) + -->

<!--     theme(axis.title.x = element_blank(), -->
<!--           legend.title = element_blank()) -->
<!-- } -->

<!-- drake::readd(SEAPSUTWorkflow::target_names$CompletedAllocationTables, path = cache_path, character_only = TRUE) %>% -->
<!--   dplyr::group_by(.data[[IEATools::iea_cols$country]]) %>%  -->


<!--     dplyr::filter(.data[[IEATools::template_cols$ef_product]] == "Electricity", -->
<!--                   .data[[IEATools::template_cols$destination]] == "Residential") %>% -->

<!--   residential_elect() +  -->

<!--   MKHthemes::xy_theme() -->

<!-- ``` -->


```{r, echo = FALSE}
alloc_graph <- function(.df, 
                        year = IEATools::iea_cols$year,
                        .values = IEATools::template_cols$.values, 
                        machine = IEATools::template_cols$machine, 
                        eu_product = IEATools::template_cols$eu_product, 
                        machine_eu_product = paste0(machine, "_", eu_product)) {
  .df %>%
    dplyr::mutate(
      "{machine_eu_product}" := paste(.data[[machine]], "->", .data[[eu_product]])
    ) %>% 
    ggplot2::ggplot(mapping = ggplot2::aes(x = .data[[year]],
                                           y = .data[[.values]],
                                           fill = .data[[machine_eu_product]])) +
    ggplot2::geom_area() +
    ggplot2::scale_x_continuous(limits = c(1960, 2020), breaks = seq(1960, 2020, by = 10)) +
    ggplot2::scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2)) +
    ggplot2::ylab("Allocation [-]") +
    MKHthemes::xy_theme() +
    theme(axis.title.x = element_blank(),
          legend.title = element_blank())
}

plots_df <- drake::readd(SEAPSUTWorkflow::target_names$CompletedAllocationTables, path = cache_path, character_only = TRUE) %>%
  dplyr::group_by(.data[[IEATools::iea_cols$country]], 
                  .data[[IEATools::template_cols$ef_product]], 
                  .data[[IEATools::template_cols$destination]]) %>% 
  tidyr::nest() %>% 
  dplyr::mutate(
    plots = purrr::map(data, alloc_graph)
  )
```




```{r}
plots_df[[IEATools::iea_cols$country]][[1]]
plots_df[[IEATools::template_cols$ef_product]][[1]]
plots_df[[IEATools::template_cols$destination]][[1]]
plots_df$plots[[1]]
```

