---
title: "PFU-Database Documentation"
author: "Zeke Marshall"
date: "14/10/2020"
output: pdf_document # HTML_document
bibliography: databasedocumentation.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load required packages

```

# PFU-Database Documentation

In this document the structure, data sources, underlying code, and methodologies used in the construction of the primary-final-useful (PFU) database are recorded.

## Energy Conversion Chain Framework

## Societal Exergy Analysis

## Data

## Final-to-Useful Allocations

## Final-to-Useful Efficiencies and Exergy-to-Energy Ratios

### Framework

Conventional, Approximate, Exact methodologies

### Machine and Useful Work Products

#### Electric Lamps - Light

#### Computers - Information processing

In societal exergy analysis the treatment of the machine-useful work product combination Computer - Information processing has been subject to neglect, with only Ayres [@Ayres2005] providing data for the final-to-useful efficiency of what he terms "Electronic signal processing".

In the PFU-Database we calculate the final-to-useful efficiency by establishing that the maximum efficiency of a computation is determined by the minimum quantity of energy required to erase one bit of information in an irreversible computer as set by the Landauer limit.

The Landauer limit is expressed in the following equation

$$
E = k_{B}Tln2
$$

Here $k_{B}$ represents the Boltzmann constant, $T$ represents the temperature of the heat sink, or the environmental temperature (termed $T_{0}$ when calculating Carnot efficiencies), and $E$ represents the quantity of energy required to erase one bit of information. In the PFU Database $T_{0}$ is assumed to represent an average room temperature of 20C.

To calculate the efficiency of a computer we require corresponding performance data, i.e. data for the number of bit operations performed per unit energy, however, such data is rare necessitating an approximate approach. To achieve this we used data provided by Koomey et al [@koomey2010implications] for "Computations per kWh", from whichKoomey's Law was established, which states *"The electrical efficiency of computation has doubled roughly every year and a half for more than six decades"*.

The performance metric "Computations" is a estimation based on the methodology in Nordhaus [@nordhaus2007two], preventing conversion into bit operations per second, consequently we used this trend as an indicator of technological progress, which we then applied to a sample of bit operations per second data points.

ZM: Utilising this approach yields a single final-to-useful exergy efficiency metric, we need to think about how to separate eta.fu and phi.u.

## Countries

## R Ecosystem for the PFU-Database

### Outline

### IEATools

### Recca

### SEAPSUTWorkflow

### PFUSetup

### PFUInterface

## Nomenclature

## References
